---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets-password-generator.yaml
  - ./secrets-db-payments.yaml
  - ./secrets-webhook.yaml
  - ./database-cluster.yaml
  - ./database-payments.yaml
  - ./database-podmonitor.yaml
  - ./payments-deployment.yaml
  - ./payments-service.yaml
  - ./payments-pdb.yaml
  - ./orders-rollout.yaml
  - ./orders-service.yaml
  - ./orders-pdb.yaml
  - ./web-rollout.yaml
  - ./web-service.yaml
  - ./web-service-canary.yaml
  - ./web-pdb.yaml
  - ./web-httproute.yaml
  - ./analysis.yaml
  - ./receipts-deployment.yaml
  - ./receipts-pvc.yaml
  - ./receipts-pdb.yaml
  - ./reset.yaml
