---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-portfolio-admin
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: grafana-portfolio-admin
  data:
    - secretKey: password
      remoteRef:
        key: portfolio/grafana
        property: admin-password
