---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana.yaml
  - ./externalsecret.yaml
  - ./datasource-prometheus.yaml
  - ./datasource-loki.yaml
  - ./datasource-tempo.yaml
  - ./dashboard.yaml
  - ./dashboard-platform.yaml
  - ./dashboard-shop.yaml
  - ./httproutefilter.yaml
  - ./httproute.yaml
  - ./networkpolicy.yaml
