---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: authentik-db
  labels:
    prometheus.homelab/instance: portfolio
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: authentik-db
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
