---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portfolio-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: portfolio-prometheus
subjects:
  - kind: ServiceAccount
    name: portfolio-prometheus
    namespace: portfolio
