---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-portfolio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-portfolio
  data:
    - secretKey: token
      remoteRef:
        key: portfolio/cloudflare
        property: tunnel-token
