---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: kafka-ui-not-found
spec:
  directResponse:
    statusCode: 404
    contentType: text/plain
    body:
      type: Inline
      inline: "Not Found"
